const button = document.querySelector("#Button");
const output = document.querySelector(".randomNames");
const Shark = document.querySelector(".randomShark");
const imgPerson = document.querySelector(".imgPerson");

function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min) + min);
}

button.addEventListener("click", () => {
  output.innerText = `${nombres[getRandomInt(0, 100)]} ${
    apellidos[getRandomInt(0, 100)]
  }`;
  Shark.innerText = FrasesDeShark[getRandomInt(0, 10)];
  displayRandomPerson();
});

async function getRandomPerson() {
  const response = await fetch("https://randomuser.me/api/");
  const data = await response.json();
  const person = data.results[0];

  const imageUrl = person.picture.large;

  return { imageUrl };
}

async function displayRandomPerson() {
  const { imageUrl } = await getRandomPerson();

  const image = document.createElement("img");
  image.src = imageUrl;
  imgPerson.appendChild(image);
}

const FrasesDeShark = [
  "toma enana",
  "ahi ta :3",
  "te quiero pegar",
  "te voy a quitar las pantaleticas",
  "vas a ve lo que te voy a hacer mmgva",
  "shark puta",
  "shark desnuita en pantaletica",
  "te wa a nalguea",
  "vas a ve te wa a jode",
  "te voy a reventar",
];

const nombres = [
  "Juan",
  "María",
  "Pedro",
  "Ana",
  "José",
  "Laura",
  "Francisco",
  "Isabel",
  "Javier",
  "Carmen",
  "Manuel",
  "Sara",
  "Luis",
  "Raúl",
  "Elena",
  "David",
  "Marta",
  "Fernando",
  "Lucía",
  "Diego",
  "Cristina",
  "Rubén",
  "Pilar",
  "Antonio",
  "Adrián",
  "Lorena",
  "Andrés",
  "Beatriz",
  "Víctor",
  "Natalia",
  "Miguel",
  "Alicia",
  "Mario",
  "Victoria",
  "Jorge",
  "Esther",
  "Roberto",
  "Silvia",
  "Álvaro",
  "Rocío",
  "Enrique",
  "Patricia",
  "Gonzalo",
  "Eva",
  "Guillermo",
  "Mónica",
  "Oscar",
  "Nerea",
  "Julio",
  "Julia",
  "Manuela",
  "Marina",
  "Ramón",
  "Paula",
  "Santiago",
  "Sofía",
  "Rafael",
  "Mireia",
  "Hugo",
  "Nuria",
  "Alfonso",
  "Celia",
  "Aitor",
  "Nacho",
  "Cristian",
  "Lucas",
  "Irene",
  "Emilio",
  "Elisa",
  "Eduardo",
  "Aurora",
  "Ángel",
  "Cecilia",
  "Rubén",
  "Ainhoa",
  "Sergio",
  "Aurora",
  "Marcela",
  "Claudia",
  "Héctor",
  "Carla",
  "Joaquín",
  "Aitana",
  "Aurora",
  "Carolina",
  "Daniel",
  "Judit",
  "Israel",
  "Gabriela",
  "Sophia",
  "Ethan",
  "Emma",
  "William",
  "Isabella",
  "Aiden",
  "Olivia",
  "James",
  "Ava",
  "Benjamin",
  "Charlotte",
];

const apellidos = [
  "García",
  "Rodríguez",
  "González",
  "Fernández",
  "López",
  "Martínez",
  "Sánchez",
  "Pérez",
  "Gómez",
  "Martín",
  "Jiménez",
  "Ruiz",
  "Hernández",
  "Díaz",
  "Moreno",
  "Álvarez",
  "Muñoz",
  "Romero",
  "Alonso",
  "Gutiérrez",
  "Navarro",
  "Torres",
  "Domínguez",
  "Vázquez",
  "Ramos",
  "Gil",
  "Serrano",
  "Blanco",
  "Ramírez",
  "Molina",
  "Suárez",
  "Ortega",
  "Delgado",
  "Castro",
  "Ortiz",
  "Rubio",
  "Santiago",
  "Fuentes",
  "Cruz",
  "Calvo",
  "Méndez",
  "Vidal",
  "Márquez",
  "León",
  "Peña",
  "Herrera",
  "Cabrera",
  "Flores",
  "Carrasco",
  "Núñez",
  "Iglesias",
  "Santos",
  "Lara",
  "Soto",
  "Sosa",
  "Garrido",
  "Espinosa",
  "Reyes",
  "Otero",
  "Vega",
  "Carmona",
  "Gallardo",
  "Vargas",
  "Aguilar",
  "Rivas",
  "Campos",
  "Estévez",
  "Mora",
  "Soria",
  "Montes",
  "Solís",
  "Arias",
  "Benítez",
  "Pascual",
  "Pereira",
  "Hidalgo",
  "Nieto",
  "Sáez",
  "Pardo",
  "Aguilera",
  "Moya",
  "Olivares",
  "Villa",
  "Salas",
  "Ferrer",
  "Valencia",
  "Medina",
  "Valverde",
  "Garriga",
  "Morales",
  "Gonzales",
  "Castellanos",
  "Reyes",
  "Fuentes",
  "Cortez",
  "Velasco",
  "Vergara",
  "Rojas",
  "Espinoza",
  "Santana",
];
